#=================================================
# Description: Build FFmpeg Docker Image using GitHub Actions
# License: MIT
#=================================================

name: ubuntu-ffmpeg

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'ssh'
        required: false
        default: 'false'

env:
  UPLOAD_BIN_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_RELEASE: true
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PWD: ${{ secrets.DOCKERHUB_PWD }}  
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04   
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}

    name: Build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target: [ctc_23.05]

    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq purge azure-cli ghc* zulu* llvm* firefox powershell openjdk* dotnet* google* mysql* php* android*
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
  

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%m/%d_%Y_%H/%M')" >> $GITHUB_ENV
          echo "date2=$(date +'%Y/%m %d')" >> $GITHUB_ENV
          echo "date3=$(date +'%m.%d')" >> $GITHUB_ENV
          echo "DOCKERTAG=${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-ffmpeg:latest" >> $GITHUB_ENV
          VERSION="$(echo "${{ github.event.action }}" | grep -Eo "[0-9.]+" | sed -e 's/ //')" || true
          if [ "$VERSION" ]; then
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "VERSION=$(date +'%m.%d')" >> $GITHUB_ENV
          fi        

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: ${{ env.DOCKERHUB_USERNAME && env.DOCKERHUB_PWD }}

      - name: Login To DockerHub
        uses: docker/login-action@v2
        if: ${{ env.DOCKERHUB_USERNAME && env.DOCKERHUB_PWD }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
            
      - name: Build and push docker image
        uses: docker/build-push-action@v4
        continue-on-error: true
        if: ${{ env.DOCKERHUB_USERNAME && env.DOCKERHUB_PWD && ! contains(github.event.action, 'noser') }}
        with:
          platforms: linux/arm64
          file: Dockerfile
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-ffmpeg:latest
            ${{ env.DOCKERTAG }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1
        with:
          retain_days: 1
          keep_minimum_runs: 0
